apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simpleapi
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: simpleapi-app
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s-manifests
    repoURL: 'git@github.com:abelclopes/simpleApi.git'
    targetRevision: HEAD
  sources: []
  project: simpleapi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
