apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: simpleApi
  namespace: argocd  # Certifique-se de que o namespace onde o ArgoCD está instalado é correto
spec:
  description: Projeto para a aplicação SimpleApi
  sourceRepos:
    - 'https://github.com/abelclopes/simpleApi.git'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: '*'
